### ISSUE TITLE
Convert AI files to SVGs

### ISSUE THREAD

**Issue by crutchcorn** [crutchcorn/frosting-icon-theme#3]
The only reason this wasn't done before is because I ran into some issues with "transformations being expanded" whatever that means... I don't get AI at times... CAN'T WE ALL JUST HAVE SOME DECENT STANDARDS ADOBE???

**Comment by danielhickman** [comment]
It looks like an issue with Inkspace SVGs (vs Plain SVGs, and option in the Inkscape exporter). I wrote a Ruby program that can remove all attributes in the `inkscape` or `sodipodi` namespaces as well as minify   it if needed (not sure what issues may arise with Linux themes with the minified SVG).

Will commit the SVGs and the program if you approve.

```ruby
Dir.foreach('./') do |dir|
	next if dir == '.' or dir == '..' or !Dir.exists?(dir)
	Dir.chdir Dir.pwd + "/" + dir
	Dir.foreach('./') do |file|
	  next if file == '.' or file == '..' or Dir.exists?(file)
		if File.readable?(file) then
			outdata = File.read(file).gsub(/(inkscape:|sodipodi:)[\w-]+="[\s\w:\/\.\-\#]+"|<!--.+-->|id="\w+"/i, "") if !ARGV.include?("--minify")
			outdata = File.read(file).gsub(/(inkscape:|sodipodi:)[\w-]+="[\s\w:\/\.\-\#]+"|<!--.+-->|id="\w+"|xmlns:?\w*="[\w:\/\.\-\#]+|^\s+|\s+$|\s+(?=\s)"/i, "") if ARGV.include?("--minify")
			File.open(file, 'w') do |out|
				out << outdata
			end 
		else
			puts "Can't read " + file
		end
	end
	Dir.chdir Dir.pwd.sub("/" + dir, "")
end
```

**Comment by crutchcorn** [comment]
Would you be able to change the program to ONLY parse SVGs? I noticed that not only do they work the best in Linux, but they open in Illustrator (unlike the originals)

**Comment by danielhickman** [comment]
https://github.com/crutchcorn/frosting-icon-theme/commit/c71f016cebfaed0794ecfefbb2b8242ef1dd3881
