### ISSUE TITLE
Please update README

### ISSUE THREAD

**Issue by ikeydoherty** [crutchcorn/frosting-icon-theme#4]
"EvoPop was a simple icon theme with some google material design inspiration built by the now defunct Solus Project design team."

Grammatically this implies that the design team of the defunct Solus Project, created the theme.

Solus Project is alive and well :P Likely better to just remove reference to Solus, git history speaks for itself.

**Comment by crutchcorn** [comment]
So sorry! This is why we got responsibly and get some sleep before commits. :P
